port: 1234
socks-port: 7891
mixed-port: 1235
allow-lan: False
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
last-yaml: xxx.yaml
last-yamlIndex: 1
system-proxy: false
subConvert: https://sub.v1.mk/
localUI: http://127.0.0.1:9090/ui/
clash-free: 
